dist: bionic
sudo: required
cache:
  directories:
  - ".m2"
services:
- docker
script:
- docker run --rm -it -v "$PWD":/usr/src/amw -v "$PWD/.m2":"/root/.m2" -w /usr/src/amw
  markhobson/maven-chrome:jdk-11 mvn clean deploy
- AMW_docker/build.sh
before_deploy:
- sudo chmod 777 AMW_ear/target/mvn-repo/ch/puzzle/itc/mobiliar/AMW_ear/*/AMW_ear-*.ear
- mv AMW_ear/target/mvn-repo/ch/puzzle/itc/mobiliar/AMW_ear/*/AMW_ear-*.ear AMW_ear-${TRAVIS_BRANCH :1}.ear
after_success:
- "[[ -z $TRAVIS_PULL_REQUEST_BRANCH ]] && export CURRENT_BRANCH=$TRAVIS_BRANCH ||
  export CURRENT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
- docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASSWORD"
- docker tag liimaorg/liima:snapshot liimaorg/liima:$CURRENT_BRANCH
- docker push liimaorg/liima:$CURRENT_BRANCH
deploy:
  provider: releases
  api_key:
    secure: E9tzuMEkm1Z8SoOJNJCFRXFY6P3wTgjvQQ4yUbY70WE9TzJ65nqncL83D+mGXz1DWmEQTbDt+ZoYyZBtcVvFsNjb/+GYBEoAI7IBi5OSAomzL3RosZB4YEM/6W4pFL+aItgaXwD+WdJbOaTbPuab5KsBzS0Vjw6MH0xb8o7ex6Eu77CkNWxLr0wchMHHMRJSPzbwQrOpsXnewoByF4tPHPJegc41AT0hjHPkWczHfUIEDs9irLNIAiSEaTzYuRwHiDrvdc02ThuZzfYcbBKBAhcCZIeS3j6ncxGl/VMdkoBpanqE+SRNaxqh4K6YzRX0LFlCZqPcRSj3+CxoYKwzdkBCjlH2dBaPAUKpMVSBkgRzp+vbaUpRPaXYJBxUBLk0b369I/2QNeC0UXVzFVYlQekQeXyC1XADi/ypKl0vwI+Mm4YH6NY6GwaEUGJWlu3TGeckeA47MiFuMBuspoQ4+v977eEPweA0wGrtqQVPD/da0nrJ/7i563bIjvObZJbJ4kb/EB6hexE+rm6Jxpg77W9AyCEE1CgYfvxw2BQcl+gR9rXj7gvDGy8H6tRpyrpZz+aWwgCKjNBg51EReE5VNqrg1m4Mjv5kyAW/GwEy/D3g+3M9Gkuk878wyL5QGMP+22e8PFylpI03vFNvZ3SDm4K5yZhz+Q1AdBWATvUIzJM=
  file_glob: true
  file: "AMW_ear-*.ear"
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
  - master
  - "/^release-.*$/"
  - "/^v1.*$/"
