cache:
  directories:
  - .m2
services:
- docker
install:
- docker run -it --name amw-install -v "$PWD":/usr/src/amw -v "$PWD/.m2":"/root/.m2"
  -w /usr/src/amw maven:3-jdk-8-alpine mvn install -DskipTests=true -Dmaven.javadoc.skip=true
  -B -V
script:
- docker run -it --name amw-test -v "$PWD":/usr/src/amw -v "$PWD/.m2":"/root/.m2"
  -w /usr/src/amw maven:3-jdk-8-alpine mvn test -B
before_deploy:
- docker run -it --name amw-deploy -v "$PWD":/usr/src/amw -v "$PWD/.m2":"/root/.m2"
  -w /usr/src/amw maven:3-jdk-8-alpine mvn deploy -f AMW_ear -B
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_API_KEY}
  file_glob: true
  file: "AMW_ear/target/mvn-repo/ch/puzzle/itc/mobiliar/AMW_ear/*/AMW_ear-*.ear"
  skip_cleanup: true
  on:
    tags: true
