sudo: required
cache:
  directories:
  - .m2
services:
- docker
script:
- docker run --rm -it -v "$PWD":/usr/src/amw -v "$PWD/.m2":"/root/.m2" -w /usr/src/amw markhobson/maven-chrome mvn clean deploy
- AMW_docker/build.sh
before_deploy:
- sudo chmod 777 AMW_ear/target/mvn-repo/ch/puzzle/itc/mobiliar/AMW_ear/*/AMW_ear-*.ear
after_success:
  - "[[ -z $TRAVIS_PULL_REQUEST_BRANCH ]] && export CURRENT_BRANCH=$TRAVIS_BRANCH || export CURRENT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  - docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASSWORD"
  - docker tag liimaorg/liima:snapshot liimaorg/liima:$CURRENT_BRANCH
  - docker push liimaorg/liima:$CURRENT_BRANCH
deploy:
  provider: releases
  api_key:
    secure: aMserxLJT49UCceWT7Ti4E7TXdWGqc0pR/Wjyh7N4OYpFlZE2tx+o7T3LrplMVpKYZy+YlWuXYizeF+uL7swVzLJL8pgVb8j+zI/CNA/UL6QwzXWW8t5Cy6Ob+mcQSeIItimvowgdZ8AAja2hBS8of3xUoESZo6DsCSVS5s8BqSiPu6oV9Ua9yoKnNs2J17FjJ23x8DUAHTTVU84FKqtFVtSI+pTIBnex/b0wVgypeFMciIUIUXrp2flQewZ0pdTAYfCrIG74VNgsTRzs9ikBK5+lr8I8se62zW1m7gOP7ycYU+HJEUrahwe4W+ckfgXv4pK50P5ZsiwfYWEeo6jzKUg5qQubX1GKDoB0+LL/sDYxq/uiQ+7Djs/UIrwsBQ8Xzt/FTQEfANA0CTIyVHv0SyL+nwSJDl4wUSwmkLx76FcZIggh45HECC63g9TBcDqZxOFttWIbYWIz15UDtbgBDSvqowEOxooU3P1FkLaHR2ZvvOCkSwLRoSH0CN5aVy3PT/XA88rkzR/IT+hAm03Yr0ZeaIY28bvwBR+VXydzKxsYYraU1b1ecAw2qhdVF1vDp7xlaVC9Aaj0+u7RdJra7WRbMf6g22LQ3e8NYP6O/hLQnS6oAXdaN+XmoNV8GT44KNkg1XEKPwOj7N1z2zOCDFcMHsgmq+8CU0tQB1O3HY=
  file_glob: true
  file: "AMW_ear/target/mvn-repo/ch/puzzle/itc/mobiliar/AMW_ear/*/AMW_ear-*.ear"
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
  - master
  - /^release-.*$/
  - /^v1.*$/
