name: run e2e tests

on:
  push:
    branches: [ master, feature/cypress-e2e-tests ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: build and run e2e tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Cache node
      uses: actions/cache@v2
      with:
        path: ~/.node
        key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-node

    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@master

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build docker image
      run: |
        cd AMW_e2e
        npm install
        npm run docker:build

    - name: Run e2e tests
      run: | 
          cd AMW_e2e
          npm run test:ci